Repository django-tastypie/django-tastypie, pull requests merged in 2018-04, with the labels that each got.

#1548 Get multiple in one query
  AUTHORS
  tastypie/resources.py
  tests/core/tests/resources.py
Labels: needunittest

#1533 Updated hyperlinks for biplist
  README.rst
  docs/index.rst
  docs/serialization.rst
  tastypie/serializers.py
Labels: ready for release

#1544 Fix for ToManyField.dehydrate with a null value regression.
  tastypie/fields.py
  tests/core/tests/fields.py
Labels: needunittest, ready for release
